version: '3.8'
services:

  talk-to-me-friend:
    container_name: talk-to-me-friend-web
    privileged: true
    working_dir: /app
    build:
      context: ./
      dockerfile: ./_infra/Dockerfile
    volumes:
      - ./:/app
    env_file:
      - ./_infra/.env
    ports:
      - "3000:3000"
      - "9856:9856"
      - "9229:9229"
      - "9000:9000"