version: '3.8'
services:

  client:
    container_name: talk-to-me-friend-client
    working_dir: /app
    build:
      context: ./client
      dockerfile: ../_infra/Dockerfile
      args:
        FOLDER_NAME: client
    network_mode: host
    volumes:
      - ./:/app
      - '/app/node_modules'
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development

  server:
    container_name: talk-to-me-friend-server
    privileged: true
    working_dir: /app
    build:
      context: ./server
      dockerfile: ../_infra/Dockerfile
      args:
        FOLDER_NAME: server
    network_mode: host
    volumes:
      - ./:/app
    env_file:
      - ./_infra/.env
    ports:
      - "9000:9000"
    environment:
      - NODE_ENV=development
    depends_on:
      - client


#       version: "3.8"
# services:
#  wl_waiting_room:
#     container_name: wl_waiting_room
#     working_dir: /app
#     build:
#       context: ./
#       dockerfile: ./infra/development/Dockerfile
#     volumes:
#       - ./:/app
#     env_file:
#       - .env
#     ports:
#       - "5000:5000"
#     networks:
#       - sympla_network_geral
#       - white-lion_comprador_sympla_net

# networks:
#   outside:
#     external: true
#   sympla_network_geral:
#     external:
#       name: sympla_network_geral
#   white-lion_comprador_sympla_net:
#     external:
#       name: white-lion_comprador_sympla_net